ERROR - 2022-12-01 18:12:39 --> mysqli_sql_exception: Duplicate entry '' for key 'fundraise.PRIMARY' in /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php:292
Stack trace:
#0 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/Database/MySQLi/Connection.php(292): mysqli->query('INSERT INTO `fu...', 0)
#1 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fu...')
#2 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fu...')
#3 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/Database/BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fu...', Array, false)
#4 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
#5 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/BaseModel.php(748): CodeIgniter\Model->doInsert(Array)
#6 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/Model.php(667): CodeIgniter\BaseModel->insert(Array, false)
#7 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/BaseModel.php(658): CodeIgniter\Model->insert(Array, false)
#8 /Users/macintoshhdd/Projects/ufundme/app/Controllers/Fundraiser.php(32): CodeIgniter\BaseModel->save(Array)
#9 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/CodeIgniter.php(902): App\Controllers\Fundraiser->create()
#10 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fundraiser))
#11 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(NULL, Object(Config\Cache), false)
#12 /Users/macintoshhdd/Projects/ufundme/public/index.php(67): CodeIgniter\CodeIgniter->run()
#13 /Users/macintoshhdd/Projects/ufundme/vendor/codeigniter4/framework/system/Commands/Server/rewrite.php(46): require_once('/Users/macintos...')
#14 {main}
CRITICAL - 2022-12-01 18:12:39 --> Duplicate entry '' for key 'fundraise.PRIMARY'
in SYSTEMPATH/Database/MySQLi/Connection.php on line 292.
 1 SYSTEMPATH/Database/MySQLi/Connection.php(292): mysqli->query('INSERT INTO `fundraise` (`user_id`, `organisation`, `cause`, `email`, `country`, `city`, `address_one`, `address_two`, `phone_number`, `target_amount`, `title`, `active`, `created_at`, `updated_at`) VALUES (\'1\', \'BidOn Technologies\', \'trying\', \'mic.costero@yahoo.com\', \'Ghana\', \'Dome\', \'Nkrumah Street, Haatso\', \'nothing\', \'0206665179\', \'30000\', \'title\', 0, \'2022-12-01 18:12:39\', \'2022-12-01 18:12:39\')', 0)
 2 SYSTEMPATH/Database/BaseConnection.php(693): CodeIgniter\Database\MySQLi\Connection->execute('INSERT INTO `fundraise` (`user_id`, `organisation`, `cause`, `email`, `country`, `city`, `address_one`, `address_two`, `phone_number`, `target_amount`, `title`, `active`, `created_at`, `updated_at`) VALUES (\'1\', \'BidOn Technologies\', \'trying\', \'mic.costero@yahoo.com\', \'Ghana\', \'Dome\', \'Nkrumah Street, Haatso\', \'nothing\', \'0206665179\', \'30000\', \'title\', 0, \'2022-12-01 18:12:39\', \'2022-12-01 18:12:39\')')
 3 SYSTEMPATH/Database/BaseConnection.php(620): CodeIgniter\Database\BaseConnection->simpleQuery('INSERT INTO `fundraise` (`user_id`, `organisation`, `cause`, `email`, `country`, `city`, `address_one`, `address_two`, `phone_number`, `target_amount`, `title`, `active`, `created_at`, `updated_at`) VALUES (\'1\', \'BidOn Technologies\', \'trying\', \'mic.costero@yahoo.com\', \'Ghana\', \'Dome\', \'Nkrumah Street, Haatso\', \'nothing\', \'0206665179\', \'30000\', \'title\', 0, \'2022-12-01 18:12:39\', \'2022-12-01 18:12:39\')')
 4 SYSTEMPATH/Database/BaseBuilder.php(1916): CodeIgniter\Database\BaseConnection->query('INSERT INTO `fundraise` (`user_id`, `organisation`, `cause`, `email`, `country`, `city`, `address_one`, `address_two`, `phone_number`, `target_amount`, `title`, `active`, `created_at`, `updated_at`) VALUES (:user_id:, :organisation:, :cause:, :email:, :country:, :city:, :address_one:, :address_two:, :phone_number:, :target_amount:, :title:, :active:, :created_at:, :updated_at:)', [...], false)
 5 SYSTEMPATH/Model.php(279): CodeIgniter\Database\BaseBuilder->insert()
 6 SYSTEMPATH/BaseModel.php(748): CodeIgniter\Model->doInsert([...])
 7 SYSTEMPATH/Model.php(667): CodeIgniter\BaseModel->insert([...], false)
 8 SYSTEMPATH/BaseModel.php(658): CodeIgniter\Model->insert([...], false)
 9 APPPATH/Controllers/Fundraiser.php(32): CodeIgniter\BaseModel->save([...])
10 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\Fundraiser->create()
11 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Fundraiser))
12 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
13 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
14 SYSTEMPATH/Commands/Server/rewrite.php(46): require_once('FCPATH/index.php')
CRITICAL - 2022-12-01 18:27:50 --> Invalid file: login.php
in SYSTEMPATH/Exceptions/FrameworkException.php on line 33.
 1 SYSTEMPATH/View/View.php(201): CodeIgniter\Exceptions\FrameworkException::forInvalidFile('login.php')
 2 SYSTEMPATH/Common.php(1142): CodeIgniter\View\View->render('login', [], true)
 3 APPPATH/Controllers/Profile.php(36): view('login', [...])
 4 SYSTEMPATH/CodeIgniter.php(902): App\Controllers\Profile->login()
 5 SYSTEMPATH/CodeIgniter.php(457): CodeIgniter\CodeIgniter->runController(Object(App\Controllers\Profile))
 6 SYSTEMPATH/CodeIgniter.php(340): CodeIgniter\CodeIgniter->handleRequest(null, Object(Config\Cache), false)
 7 FCPATH/index.php(67): CodeIgniter\CodeIgniter->run()
 8 SYSTEMPATH/Commands/Server/rewrite.php(46): require_once('FCPATH/index.php')
